### ISSUE TITLE
semi-parametric detection function

### ISSUE THREAD

**Issue by yuan2** [fbachl/inlabru#11] opened 2016-11-07 15:54 UTC

**Comment by finnlindgren** [comment] 2016-11-07 16:16
Description of the issue is missing. Is this a bug report, or a duplicate of issue #4 ?

**Comment by fbachl** [comment] 2016-11-07 16:20
Somewhere in between and I told Joyce to add this issue. The SP detection function needs a particular hack that is sort of independent from the general DFun interface.

**Closed** 2016-11-08 09:22 UTC
